### PR TITLE
Add excercise on body-part-predictions - will remove outputs later

### PR DESCRIPTION
**Pull request by meiler**
NB! remove outputs before merging.

### CODE REVIEW

**Comment by meiler** [comment]
I'm thinking this as the basic outline for the exercises. I don't know if we should make them score all the images they collect or train on them. 
If they need to train, then we should really do a train/valid split or something. But that might be a bit too much for the little amount of data that I expect them to collect.

**Comment by mholmjensen** [comment]
@meiler Nice

**Comment by mholmjensen** [comment]
@meiler Nice!
For training (if this is even possible timewise): 
1) We could use images from Group Y as validation for Group X? So they just have to point their evaluation generator to a different dir. 
2) We could let them overfit their own data, then see what this means for new samples (i.e. whether they destroy performance on our transfer learned model).

**Comment by meiler** [comment]
@mholmjensen @malenasj I have put the old master into https://github.com/leoilab/deeplearning-workshop/tree/deeplearning-dis-sep-2018

And will now merge this 👍 Well done!

**Pull request merged**
